### ISSUE TITLE
Did mess with Atsu months ago, atsumeru.service not found

### ISSUE THREAD

**Issue by t-lessy** [Atsumeru-xyz/Atsumeru#12]
Ok, I finally writing it. I tried to install Atsumeru months ago, but was not happy about separated Atsu and AtsuManager (and smth more, not remember). Even then it all was strange and cursed. In these months I rarely had to see error `Failed to <<act>> <<app>>.service: Unit atsumeru.service not found.`. First time I catch that error is when I tried to reinstall Audiobookshelf instance, which is completely refuse to start with the error as output. There was some more cases, fully identical to first at output part. Like, I want to "apt remove cockpit*", but also the same error linked to RustDesk:
```sh
...
Setting up rustdesk (1.3.1) ...
Failed to start rustdesk.service: Unit atsumeru.service not found.
...
...
```

In '/etc/systemd/system/' I have neither Atsumeru.service and atsumeru.service.

Latest install script from SystemD repo gave no one line, even the script is empty.

Older scripts gives outputs below:
```sh
# atsu-install-old.sh
Enter the port for atsumeru web service (press ENTER if port 31337 suits you) 
The server will listen on the default port -> 31337
Java JRE -
/usr/bin/java
Found Java executable in PATH
Version 21.0.4
No URLs found in -.
```

```sh
# atsu-install-old-2.sh
# There was a TUI
/usr/bin/java
```

```sh
# atsu-uninstall.sh
Failed to stop atsumeru.service: Unit atsumeru.service not loaded.
```

I have old script for Atsumeru, which was downloaded for installing Atsu first time. Maybe, it can be compared to other versions, at least.

Thanks for attention! Sorry for ignoring the problem for months. 😅

**Comment by t-lessy** [comment]
For You to be noticed, I do not have any critical problems right now. If I will supposed to recreate "environment" which will has need to resolve the problem with Atsumeru.service, I'll just install Audiobookshelf. Right now I only wanna find first step in this error and, potentially, resolve it, but do not have huge need.

**Comment by Metaroka** [comment]
What instructions did you use to install atsumeru?

**Comment by t-lessy** [comment]
Okaaay, trying to add the file on mobile... 🥲

**Comment by t-lessy** [comment]
Sorry, cannot add script file right now. There is a link for it on GDrive. 😅
[atsu-install.sh](https://drive.google.com/file/d/1GHKgR8UPYek4HlcLbfiA5i-L-QlyIL4L/view?usp=drivesdk)

**Comment by Metaroka** [comment]
I'm sorry, but I don't understand how you got it so wrong.

`Failed to start rustdesk.service: Unit atsumeru.service not found.`

**Summary of the Script's Functionality**

The script automates the **installation**, **updating**, and **uninstallation** of the **Atsumeru server service** on a Linux system using `systemd`. It provides a text-based user interface (TUI) using `whiptail` for easy interaction.

### Key Features

#### 1. Installation

- **Prerequisite Checks**
  - Ensures the script is **not run as `root`**.
  - Verifies the `sudo` password.
  - Checks if **Java is installed**; if not, offers to install **OpenJRE 11**.
  - Confirms that at least **1 GB of RAM** is available.

- **User Input**
  - Prompts the user to specify the **web server port** (default is `31337`).

- **User and Directory Setup**
  - Creates a dedicated system user `atsumeru` to run the service.
  - Sets up the installation directory at `/opt/atsumeru`.

- **Download and Install**
  - Fetches the latest Atsumeru `.jar` file from GitHub.
  - Creates an environment file `.env` with necessary variables.
  - Generates a `systemd` service file for Atsumeru.

- **Service Activation**
  - Runs the following commands to start and enable the service:

    ```bash
    sudo systemctl daemon-reload
    sudo systemctl start atsumeru.service
    sudo systemctl enable atsumeru.service
    ```

  - Retrieves and displays the **admin password** from service logs.
  - Provides the user with the web interface URL.

#### 2. Update

- **Service Status Check**
  - Ensures the Atsumeru service is currently running.

- **Version Comparison**
  - Downloads the latest version and compares it with the installed one.

- **Upgrade Process**
  - If an update is available:
    - Stops the service:

      ```bash
      sudo systemctl stop atsumeru.service
      ```

    - Replaces the `.jar` file.
    - Restarts the service:

      ```bash
      sudo systemctl start atsumeru.service
      ```

- **Service Restart**
  - Confirms the service is running correctly after the update.

#### 3. Uninstallation

- **Component Selection**
  - Allows the user to choose which components to remove:
    - The **Atsumeru service**.
    - The **server directory** (deletes all files in `/opt/atsumeru`).
    - **OpenJRE 11** from the system.

- **Removal Process**
  - Stops and disables the Atsumeru service:

    ```bash
    sudo systemctl stop atsumeru.service
    sudo systemctl disable atsumeru.service
    sudo systemctl daemon-reload
    ```

  - Deletes the `atsumeru` user and its home directory (if selected):

    ```bash
    sudo userdel -r atsumeru
    ```

  - Uninstalls OpenJRE 11 (if selected):

    ```bash
    sudo apt purge openjdk-11-jre -y
    sudo apt autopurge -y
    ```

**Comment by t-lessy** [comment]
Well... I tried to remove Atsumeru's user and dir, and then install it again. Newest script (root of Atsu Systemd repo) stops at:
```sh
z@neoryxsa:~/oh/Atsumeru-systemd$ ./install.sh 

/usr/bin/java
Please wait a minute...
```
... without creating systemd service as it expected to. When I tried to recreate Atsu's systemd unit service, it failing with:
```sh
Oct 12 20:00:32 neoryxsa java[360964]: Error: Invalid or corrupt jarfile Atsumeru.jar
```
... Even tried to give executable status to jar, and giving absolute path to jar. It doesn't work.

Then I tried to download and copy the jar to /opt/atsumeru. It worked! Old jar is empty, completely.
Could You give me instructions, how to debug the script step-by-step? I understand that it is failed to download executable jar and create unit, but have no experience in scripting.

**Comment by t-lessy** [comment]
I tried to curl the script like in Atsumeru's Systemd page. It is linked to not existing repository. How long did you move the repository and changed the installation wiki? Could it be, that several months ago I had reading older Wiki, when actual installation  was changed?

```sh
z@neoryxsa:~/oh$ curl https://api.github.com/repos/AtsumeruDev/Atsumeru-systemd/releases/latest
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/584429037/releases/latest",
  "documentation_url": "https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api#follow-redirects"
}

```

**Comment by OlegEnot** [comment]
Link problems after moving the repository. Links have been fixed.
If your distribution has the openjdk-11-jre package in its repository, the installation should proceed normally, as it did for me during the test installation.
Thank you!
